### ISSUE TITLE
Exposed Slack link

### ISSUE THREAD

**Issue by santheo** [dima42/Big-Board#26]
Hi! I got several emails from Slack and GitGuardian about an exposed Slack web hook in this repo. You can see it here:

https://dashboard.gitguardian.com/core-alerting/incident-resolution/c8f54775-0d2b-4db3-8c23-13aa916558f4/

The Slack instance isn't in use and they revoked the web hook, but could you remove it anyway, so I don't get sent alerts in the future? I think there may be more than one place where it's mentioned; I got a few alerts about it. Thanks!

**Comment by dima42** [comment]
Thanks for the heads up.  Sorry, that link doesn't seem to work for me (probably because it's been a couple months).  Let me know if still a problem, and if so could you attach some permanent log?

**Comment by santheo** [comment]
I haven't gotten any more alerts, so I guess it's fine for now. I'll reopen this if I hear back from them.
